routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\MatchController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MatchRoundsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])
    ->name('home');


Route::resource('match', MatchController::class);

Route::get('/match/join/{match_id}', [MatchController::class, 'join'])
    ->name('match.join');


Route::get('/match-round/create/{match_id}', [MatchRoundsController::class, 'store'])
    ->name('matchRounds.store');

app/Models/MatchHistory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MatchHistory extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'match_id',
        'match_round_id',
        'player_type',
        'row',
        'column',
    ];

    public function match()
    {
        return $this->belongsTo(MatchModel::class);
    }
}

app/Models/MatchModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;


class MatchModel extends Model
{
    use HasFactory;

    public const DEFAULT_SIZE = 3;
    public const FIRST_PLAYER_TYPE = 1;
    public const SECOND_PLAYER_TYPE = 2;
    protected $table = 'matches';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_player_name',
        'second_player_name',
        'token',
    ];

    public static function generateToken(): string
    {
        return (string) Str::uuid();
    }

    public static function getPlayerTypes(?int $type = null)
    {
        $types = [
            self::FIRST_PLAYER_TYPE => 'x',
            self::SECOND_PLAYER_TYPE => 'o',
        ];

        if ($type !== null) {
            return $types[$type] ?? null;
        }

        return $types;
    }

    public function setToken(): void
    {
        $this->token = self::generateToken();
    }

    public function matchRounds()
    {
        return $this->hasMany(MatchRound::class, 'match_id', 'id');
    }

    public function countMatchRounds()
    {
        return $this->hasMany(MatchRound::class, 'match_id', 'id')->count();
    }

    public function matchRoundLatest()
    {
        return $this->hasOne(MatchRound::class, 'match_id', 'id')->latest();
    }
}

app/Models/MatchRound.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MatchRound extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'match_id',
    ];

    public function match()
    {
        return $this->belongsTo(MatchModel::class);
    }

    public function matchHistories()
    {
        return $this->hasMany(MatchHistory::class, 'match_round_id', 'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MatchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MatchModel;
use App\Services\MatchService;
use App\Services\MatchRoundService;
use App\Services\MatchHistoryService;

class MatchController extends Controller
{
    public function index()
    {
        $matches =  MatchService::get();
        return view('match.index', compact(['matches']));
    }

    public function create()
    {
        $match = MatchService::create();
        return redirect(route('match.show', $match->id) . "?round={$match->round->id}&token={$match->token}");
    }

    public function show(Request $request, MatchModel $match)
    {
        $token = $request->query('token');
        $round = $request->query('round');
        $player_type = $request->query('player_type') ?? 1;
        abort_unless($token && $round, 404);

        $matchByToken = MatchService::getFirstByToken($token);
        abort_unless($match->id === $matchByToken->id, 404);

        $matchRound = MatchRoundService::find($round);
        abort_unless($matchRound && $matchRound->match_id === $match->id, 404);

        $matchSize = MatchModel::DEFAULT_SIZE;
        $firstPlayerType = MatchModel::FIRST_PLAYER_TYPE;
        $secondPlayerType = MatchModel::SECOND_PLAYER_TYPE;

        $preparedData = MatchHistoryService::getPreparedData($match, $round, $matchSize);



        return  view('match.show', compact(
            'match',
            'matchSize',
            'preparedData',
            'round',
            'firstPlayerType',
            'secondPlayerType',
            'player_type'
        ));
    }

    public function join($match_id)
    {
        $matchToJoin =  MatchService::findWithData($match_id);
        $match = $matchToJoin['match'];
        $preparedData = $matchToJoin['preparedData'];

        if (!$match || !isset($preparedData))
            return redirect()->back()->withErrors(['match' => 'The match id was not found']);
        if ($preparedData['isFullMatchField'])
            return redirect()->back()->withErrors(['match' => 'The match is over, start a new one']);
        // return $match;
        return redirect(route('match.show', $match->id) . "?round={$match->matchRoundLatest->id}&token={$match->token}&playerType=2");
    }

    public function updatePlayersName(Request $request, $match_id)
    {
        MatchService::updatePlayerNames($match_id, (object) $request->all());
        return response('ok', 200);
    }
}

app/Http/Controllers/MatchHistoryController.php
<?php

namespace App\Http\Controllers;

use App\Services\MatchHistoryService;
use App\Http\Requests\StoreMatchHistory;

class MatchHistoryController extends Controller
{
    public function store(StoreMatchHistory $request)
    {
        $matchData = MatchHistoryService::create($request->validated());
        return $matchData;
    }
}

app/Http/Controllers/MatchRoundsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MatchModel;
use App\Services\MatchRoundService;

class MatchRoundsController extends Controller
{
    public function store($match_id)
    {
        $matchRound = MatchRoundService::create($match_id);
        return redirect(route('match.show', $matchRound->match->id) . "?round={$matchRound->id}&token={$matchRound->match->token}");
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
        return redirect()->route('match.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html  lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- Styles CSS -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
</head>
<body>

    <div class="title-container">
        <div class="title-content">
            <h1 class="text-center my-5 d-inherit">{{ config('app.name', 'Laravel') }}</h1>
            <img src="/img/tick-tack.jpg" width="73" />
        </div>
    </div>
       
        @yield('content')

    <script src="{{ mix('/js/app.js') }}"></script>
</body>
</html>

resources/views/match/index.blade.php
@extends('layouts.app')
@section('content')
<div class="text-center" id="join">

    @if ($errors->any())

    <div class="alert alert-danger" role="alert">
        <p class="mb-0">{{ 'Errors' }}</p>
        <ul class="mb-0">

            @foreach ($errors->all() as $error)

                <li>{{ $error }}</li>

            @endforeach

        </ul>
    </div>

@endif

    <a href="{{ route('match.create') }}" class="btn btn-primary btn-lg">Nueva Partida</a>
    <join-match></join-match>
    {{-- <a href="{{ route('match.show',1) }}" class="btn btn-secondary btn-lg">Join to match</a> --}}

    <div class="container mt-4">
        <table class="table table-dark table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Jugadores</th>
                <th scope="col">Rondas Jugadas</th>
            </tr>
            </thead>
            <tbody>
{{-- {{$matches}} --}}
            @foreach ($matches as $match)
            <tr>
                <th scope="row">{{ $match->id }}</th>
                <td>{{ $match->first_player_name }} | {{ $match->second_player_name }}</td>
                <td>{{ $match->countMatchRounds() }}</td>
            </tr>
            @endforeach
</div>
   

@endsection

resources/views/match/show.blade.php
@extends('layouts.app')
@section('content')
    <script>
       setTimeout(() => 
            window.event.$emit("matchData", {
                preparedData : @json($preparedData),
                match : @json($match),
                matchSize : {{$matchSize}},
            }
        ), 150);

    </script>

    <div class="container">

        <div class="d-flex justify-content-end m-3 align-items-center">
            ID del Juego  &nbsp;<span style="font-size: 1.5em">{{$match->id}}</span>
        </div>
  
        <div class="w-100" id="ticktack">

        <players-name></players-name>
            <tick-tack-toe></tick-tack-toe>
        </div>
        
        <hr>

        <div class="row">
            <div class="col-sm text-center pb-3">
                {{ link_to_route('matchRounds.store','Jugar de Nuevo', ['match_id'=> $match->id], ['class' => 'btn btn-primary']) }}
            </div>
            <div class="col-sm text-center pb-3">
                {{ link_to_route('match.create', 'Nueva Partida', [], ['class' => 'btn btn-success']) }}
            </div>
            <div class="col-sm text-center pb-3">

                {{ link_to_route('match.index', 'Home', [], ['class' => 'btn btn-info']) }}

            </div>
        </div>
    </div>


   

@endsection